#!/bin/bash
#
# Build by directory instead of by package name.

set -e

# Canonicalize distdir for ancestor check
XBPS_DISTDIR="$(readlink -f "$(xdistdir)")" || exit 1

# Extract last argument.
pkgdir="$(readlink -f "${*: -1}")"

# In case we were passed a template, set pkgdir to parent.
if [[ "${pkgdir##*/}" = "template" ]]; then
	pkgdir="${pkgdir%/*}"
fi

# We probably weren't passed a path to a template,
# could've been another target (like clean) or a package already in distdir.
[[ ! -f "${pkgdir}/template" ]] && { "${XBPS_DISTDIR}/xbps-src" "$@"; exit 1; }

pkgname="${pkgdir##*/}"

# Package already in distdir
if [[ -n "$(find "${XBPS_DISTDIR}/srcpkgs" -samefile "$pkgdir" -print -quit)" ]]; then
	"${XBPS_DISTDIR}/xbps-src" "$@" "$pkgname"
	exit 0
fi

xbps_pkgdir="${XBPS_DISTDIR}/srcpkgs/${pkgname}"

# Sanitize before copying.
rm -rf "$xbps_pkgdir"
cp -r "$pkgdir" "$xbps_pkgdir"

# Remove last argument $@.
set -- "${@:1:$#-1}"
"${XBPS_DISTDIR}/xbps-src" "$@" "$pkgname"
